### ISSUE TITLE
Empty Cavities

### ISSUE THREAD

**Issue by DetlevCM** [lvpp/sigma#3]
Dear all,

looking through the list of GAMESS COSMO cavities, I stumbled across files that lack the cavity data.
I did not (!!) check all files manually that caused an issue, however the ones I did check by hand were indeed lacking the cavity data, which makes me suspect the same is true for the other files in the list.

_This is the list I obtained:_

> 1,2,3-TRIMETHYLBENZENE
> 1,4-DIMETHYLNAPHTHALENE
> 1,5-DIMETHYLNAPHTHALENE
> 1-BUTYNE
> 1-OCTYNE
> 2,3-PENTADIENE
> 2-BUTYNE-1,4-DIOL
> 2-HEPTYNE
> 2-HEXYNE
> 3-DECYNE
> 3-HEPTYNE
> 3-METHYL-1-HEXYNE
> 4-METHYL-1-HEXYNE
> 4-METHYL-1-PENTYNE
> 4-METHYL-2-HEXYNE
> 5-METHYL-1-HEXYNE
> 5-METHYL-2-HEXYNE
> A-PINENE
> ETHYLACETYLENE
> ETHYL_CYANOACETATE
> ETOSO3-1
> FRUCTOSE
> HEPTENE-6-NITRILES
> HEXAMETHYLPHOSPHORAMIDE
> IBUPROFEN
> ISO-VALERONITRILE
> LINALOOL
> METHYLGLUTARONITRILE
> MPY+1
> PARACETAMOL
> PENTANOIC_ACID
> SACCHAROSE
> TCB-1

**Comment by rpseng** [comment]
Dear Detlev,

Thanks for reporting this. The result files for GAMESS molecules can be very large. This is because we are optimizing the geometry and all iterations are stored.

Since we are interested only in the converged result we run a post-processing code to remove unnecessary information. There is probably a bug on this code leaving some molecules without the sigma-profile.

We will try to fix this soon and then provide a new release.

**Comment by rpseng** [comment]
This is apparently fixed in the latest release.
